CREATE TABLE SUPERHERO(
	ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL
);

INSERT INTO SUPERHERO VALUES (1, 'Batman', 50.0, 85.0);
INSERT INTO SUPERHERO VALUES (2, 'Spiderman', 65.0, 65.0);
INSERT INTO SUPERHERO VALUES (3, 'Thor', 45.0, 30.0);
INSERT INTO SUPERHERO VALUES (4, 'Deadpool', 25.0, 69.0);
INSERT INTO SUPERHERO VALUES (5, 'Hulk', 30.0, 20.0);
INSERT INTO SUPERHERO VALUES (6, 'Captain America', 70.0, 75.0);
INSERT INTO SUPERHERO VALUES (7, 'Superman', 85.0, 45.0);

--Write a query to print the NAMEs of the superheroes
--where NAME has fewer than 7 chars
--Sort output by ID increasing order

--Solution query

SELECT NAME FROM SUPERHERO
WHERE LENGTH(NAME) < 7
ORDER BY ID ASC;