CREATE TABLE EMPLOYEE (
  id INTEGER PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  age INTEGER NOT NULL,
  address VARCHAR(25) NOT NULL,
  salary INTEGER NOT NULL
);

CREATE TABLE EMPLOYEE_UIN (
  id INTEGER PRIMARY KEY,
  uin TEXT NOT NULL
);

INSERT INTO EMPLOYEE VALUES (1, 'Sherrie', 23, 'Paris', 74635);
INSERT INTO EMPLOYEE VALUES (2, 'Paul', 30, 'Sydney', 72167);
INSERT INTO EMPLOYEE VALUES (3, 'Mary', 24, 'Paris', 75299);
INSERT INTO EMPLOYEE VALUES (4, 'Sam', 47, 'Sydney', 46681);
INSERT INTO EMPLOYEE VALUES (5, 'Dave', 22, 'Texas', 11843);

INSERT INTO EMPLOYEE_UIN VALUES (1, '57520-0440');
INSERT INTO EMPLOYEE_UIN VALUES (2, '49638-001');
INSERT INTO EMPLOYEE_UIN VALUES (3, '63550-194');
INSERT INTO EMPLOYEE_UIN VALUES (4, '68599-6112');
INSERT INTO EMPLOYEE_UIN VALUES (5, '63868-453');

--Generate a list of all employees who are less than 25 years old
--first in order of NAME, then of ID, both ascending.
--Result should return UIN followed by NAME

--Solution query

SELECT EMPLOYEE_UIN.uin, EMPLOYEE.name
FROM EMPLOYEE
JOIN EMPLOYEE_UIN ON (EMPLOYEE.id = EMPLOYEE_UIN.id)
WHERE EMPLOYEE.age < 25
ORDER BY EMPLOYEE.name asc, EMPLOYEE.id asc;